services:
  ts-webserver-bhavibhavan-actual:
    image: tailscale/tailscale:latest
    container_name: ts-webserver-bhavibhavan-actual
    hostname: bhavibhavan-actual
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/actual.json
    volumes:
      - ./ts/state:/var/lib/tailscale
      - ./ts/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  actual_server:
    image: actualbudget/actual-server:latest-alpine
    volumes:
      - ./actual-data:/data
    restart: unless-stopped
    environment:
      - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=200
      - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=200
      - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=200
    network_mode: service:ts-webserver-bhavibhavan-actual
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
